trigger:
  branches:
    include:
      - main

stages:
  - stage: ValidateOauthToken
    displayName: 'Validate Oauth Token'
    jobs:
      - job: RenewToken
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Requesting new OAuth token..."
            displayName: 'Fetch new OAuth token'

  - stage: ValidateStorageAccessPolicy
    displayName: 'Validate storage access policies'
    dependsOn: ValidateOauthToken
    jobs:
      - job: CheckStoragePolicy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Checking access to mounted DBFS path..."
            displayName: 'Validate DBFS Mount'

  - stage: RetryJob
    displayName: 'Retry Databricks Job with Delay'
    dependsOn: ValidateStorageAccessPolicy
    jobs:
      - job: TriggerJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Trigger job ..."
              RESPONSE=$(curl --location 'https://dbc-bd38953b-53cc.cloud.databricks.com/api/2.1/jobs/run-now' \
                --header 'Authorization: Bearer dapiccb98aad2dda701c33f67fb4fba4fe2f' \
                --header 'Content-Type: application/json' \
                --data '{
                  "job_id": 477162549764416
                }')
              echo "Databricks API Response:"
              echo "$RESPONSE"
            displayName: 'Run file generation job'
